// <auto-generated />
namespace Incidencias.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_titulo_incidencia_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_titulo_incidencia_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201512291841291_add_titulo_incidencia_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
