// <auto-generated />
namespace Incidencias.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Tecnico_Contacto_Aplicacio_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Tecnico_Contacto_Aplicacio_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201601021027476_add_Tecnico_Contacto_Aplicacio_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
